# Generated by Django 3.1.5 on 2021-08-13 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sale_sold_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_sold',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
