# Generated by Django 3.1.5 on 2021-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210813_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_value', models.FloatField(default=0)),
                ('sales_value', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
