# Generated by Django 3.1.5 on 2021-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210816_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossprofit',
            name='profit_or_loss',
            field=models.FloatField(default=0),
        ),
    ]
